### ISSUE TITLE
Wording incorrect on 'Getting started with the Amazon Kendra console'

### ISSUE THREAD

**Issue by sengstacken** [awsdocs/amazon-kendra-developer-guide#11]
https://docs.aws.amazon.com/kendra/latest/dg/gs-console.html

On step 3, part 1 it states - "In the navigation pane, choose Search console."

It should say "In the navigation pane, choose "Search indexed content."

**Comment by rmerrett** [comment]
This was updated a while back. I have made sure latest version included in the open source version of the docs. Thanks!
