### ISSUE TITLE
how to use submit feedback api in aws lex

### ISSUE THREAD

**Issue by vinaykumar-buram** [awsdocs/amazon-kendra-developer-guide#13]
how to use submit feedback api in aws lex

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
