### ISSUE TITLE
Unable to find source doc for webcrawler

### ISSUE THREAD

**Issue by quixoticmonk** [awsdocs/amazon-kendra-developer-guide#6]
**Reference link** : https://docs.aws.amazon.com/kendra/latest/dg/getting-started-webcrawler.html
The link to edit the doc takes me to **https://github.com/awsdocs/amazon-kendra-developer-guide/tree/master/doc_source/getting-started-webcrawler.md** which doesn't exist.

The webcrawler documentation has a few typos which I wanted to correct and open a PR.

`Choose Source Sitemaps to enter the **wesbite** sitemap URLs you want to crawl. A **sitempas** includes all relevant webpages or website domains you want to crawl. Enter the sitemap URL, and then choose Add new URL. You can add up to three sitemap URLs.`

**Comment by rmerrett** [comment]
Thanks for the feedback! This doc published with the corrections, but it had not published on GitHub right away. The correct version is now published on GitHub: https://github.com/awsdocs/amazon-kendra-developer-guide/blob/master/doc_source/getting-started-webcrawler.md
