### ISSUE TITLE
Document count per data source

### ISSUE THREAD

**Issue by quixoticmonk** [awsdocs/amazon-kendra-developer-guide#9]
Reference document : https://github.com/awsdocs/amazon-kendra-developer-guide/blob/master/doc_source/monitoring-runsync.md

Isn't this an index level metric ? The document mentions this as a data source level metric. _The total number of documents indexed from this data source._

**Comment by quixoticmonk** [comment]
Bumping this for clarity . The Data sources in a Kendra index do not have a document count graph for that index ( at least in GA).

**Comment by rmerrett** [comment]
Hm, the docs have stated this is an index metric since almost a year ago, so looks right my end. I will make sure another version/wrong version of the page did not linger around anywhere in the open source version of the docs. Thanks!
